services:
  # A Docker web service
  - type: web
    name: infisical-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: false
    # healthCheckPath: /

  - type: web
    name: infisical-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: false
    # healthCheckPath: /api/status
    envVars:
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: JWT_SIGNUP_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_SERVICE_SECRET
        generateValue: true
      - key: MONGO_URL
        sync: false
